{% set name = "intake-dremio" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7e2268a5b8b70aa65b4c82c91bc821114dfe6567f315c75c2e01a2854bff55d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - intake
    - pandas
    - python >=3.7
    - pyarrow >=4.0
    - libarrow-flight

test:
  imports:
    - intake_dremio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-dremio
  summary: Intake driver to load data from Dremio
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - philippjfr
